apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metasploit.fullname" . }}
  labels:
    {{- include "metasploit.labels" . | nindent 4 }}
data:
  msfconsole.sh: |
   #!/bin/bash
   /usr/src/metasploit-framework/msfconsole -r /usr/src/metasploit-framework/docker/msfconsole.rc -y $APP_HOME/config/database.yml