apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metasploit.fullname" . }}
  labels:
    {{- include "metasploit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metasploit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metasploit.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "metasploit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/bash"]
          tty: true
          stdin: true
          env:
            - name: DATABASE_URL
              valueFrom:
                  secretKeyRef:
                    name: {{ include "metasploit.fullname" . }}
                    key: database-url
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4444
              protocol: TCP
              name: metasploit
            # - name: http
            #   containerPort: 80
            #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: metasploit
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: metasploit
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ms-claim0
              mountPath: /home/msf/.msf4
              
            - name: msfconsole
              mountPath: /bin/msfconsole.sh
              subPath: msfconsole.sh

 
      restartPolicy: Always
      volumes:
        - name: ms-claim0
          persistentVolumeClaim:
            claimName: {{ include "metasploit.fullname" . }}-ms-claim
        - name: msfconsole
          configMap:
            name: {{ include "metasploit.fullname" . }}
            defaultMode: 0777

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
