apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "metasploit.labels" . | nindent 4 }}
  name: {{ include "metasploit.fullname" . }}-ms-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
