{{- if .Values.priviliges.useServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevenom.fullname" . }}
  labels:
    {{- include "kubevenom.labels" . | nindent 4 }}

---
{{- if ne .Values.priviliges.bindClusterRole "" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevenom.fullname" . }}
  labels:
    {{- include "kubevenom.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.priviliges.bindClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevenom.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
