title: Metasploit
baseurl: '/metasploit-framework'
url: ''

permalink: pretty

heading_anchors: true
aux_links_new_tab: true
aux_links:
  'Metasploit Framework on GitHub':
    - '//github.com/rapid7/metasploit-framework'

nav_cache: true

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/rapid7/metasploit-framework'
gh_edit_branch: 'master'
gh_edit_source: docs
gh_edit_view_mode: 'tree'

ga_tracking: UA-4622520-7
ga_tracking_anonymize_ip: true

# Build settings
theme: just-the-docs
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

back_to_top: true
back_to_top_text: 'Back to top'

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: development

exclude:
  - '*.rb'
  - metasploit-framework.wiki
  - README.md

just_the_docs:
  collections: []

ignore_theme_config: true
